### ISSUE TITLE
Use GMP is broken in Chapel

### ISSUE THREAD

**Issue by matthewsedam** [matthewsedam/cryptotrade#61]
Use GMP is broken in Chapel

Fix this or file a bug report in Chapel and fix it there.

**Comment by ben-albrecht** [comment]
Hi,

Are you still encountering this error? Did you [build Chapel with GMP enabled](http://chapel.cray.com/docs/master/modules/standard/GMP.html#using-the-gmp-module)?

**Comment by matthewsedam** [comment]
As of the last Travis CI build, the Chapel compiler would give an internal error when `use GMP;` was added to one of the files. I have build the Docker image with GMP and LLVM support.

**Comment by ben-albrecht** [comment]
According to your docker file, this is using Chapel 1.15.0 with `CHPL_GMP=system` and GMP 10 - is that correct?

We do nightly testing against GMP 6, which is what `CHPL_GMP=gmp` uses, so the GMP-version may be an issue (but I can't imagine why).

> file a bug report in Chapel 

It would be appreciated if you could submit an issue to the [Chapel issues page](https://github.com/chapel-lang/chapel/issues).

**Comment by matthewsedam** [comment]
Moving to Python. See #67.
